# Generated by Django 4.1.3 on 2022-12-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='money',
        ),
        migrations.AddField(
            model_name='user',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='sale',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
