# Generated by Django 4.1.3 on 2022-12-05 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_money_user_amount_user_sale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
