# Generated by Django 4.1.3 on 2022-12-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_amount_alter_user_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sale',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
