# Generated by Django 4.1.3 on 2022-12-12 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_remove_product_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ManyToManyField(related_name='basket_owner', to=settings.AUTH_USER_MODEL)),
                ('product', models.ManyToManyField(to='product.product')),
            ],
        ),
    ]
