# Generated by Django 4.1.3 on 2022-12-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_remove_basket_owner_remove_basket_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
