# Generated by Django 4.1.3 on 2022-12-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_basket_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
