# Generated by Django 4.1.3 on 2022-12-05 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basket', '0003_remove_basket_product_basket_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='owner',
        ),
        migrations.AddField(
            model_name='basket',
            name='owner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
