# Generated by Django 4.1.3 on 2022-12-05 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basket', '0004_remove_basket_owner_basket_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='owner',
            field=models.ManyToManyField(related_name='basket_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
