# Generated by Django 4.1.3 on 2022-12-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_rename_product_basket_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='amount',
        ),
    ]
