# Generated by Django 4.1.3 on 2022-12-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0010_alter_basket_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='tite',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
