# Generated by Django 4.1.3 on 2022-12-26 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_owner'),
        ('basket_detail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketdetail',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product', to='product.product', verbose_name='product'),
            preserve_default=False,
        ),
    ]
