# Generated by Django 4.1.3 on 2022-12-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket_detail', '0002_basketdetail_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketdetail',
            name='basket',
        ),
    ]
