# Generated by Django 4.1.3 on 2022-12-28 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_amount'),
        ('basket_detail', '0004_alter_basketdetail_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='basket_detail_product', to='product.product', verbose_name='product'),
        ),
    ]
